//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGULF.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Company {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Company() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EGULF.App_LocalResources.Company", typeof(Company).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string btn_del {
            get {
                return ResourceManager.GetString("btn_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btn_edit {
            get {
                return ResourceManager.GetString("btn_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar colaboradores.
        /// </summary>
        public static string btn_invite {
            get {
                return ResourceManager.GetString("btn_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string btn_new {
            get {
                return ResourceManager.GetString("btn_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud minima debe ser 10.
        /// </summary>
        public static string error_minlength_rfc {
            get {
                return ResourceManager.GetString("error_minlength_rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La compañía ya se encuentra registrada.
        /// </summary>
        public static string error_name {
            get {
                return ResourceManager.GetString("error_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliza el formato con lada, deben ser 10 dígitos.
        /// </summary>
        public static string error_phone {
            get {
                return ResourceManager.GetString("error_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El RFC ya se encuentra registrado.
        /// </summary>
        public static string error_unique_rfc {
            get {
                return ResourceManager.GetString("error_unique_rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Compañía.
        /// </summary>
        public static string title_create {
            get {
                return ResourceManager.GetString("title_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Compañía.
        /// </summary>
        public static string title_edit {
            get {
                return ResourceManager.GetString("title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Compañía.
        /// </summary>
        public static string title_index {
            get {
                return ResourceManager.GetString("title_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string txt_address {
            get {
                return ResourceManager.GetString("txt_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso!.
        /// </summary>
        public static string txt_aviso {
            get {
                return ResourceManager.GetString("txt_aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string txt_col_date {
            get {
                return ResourceManager.GetString("txt_col_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string txt_col_email {
            get {
                return ResourceManager.GetString("txt_col_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre fiscal.
        /// </summary>
        public static string txt_col_name {
            get {
                return ResourceManager.GetString("txt_col_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string txt_col_status {
            get {
                return ResourceManager.GetString("txt_col_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la empresa.
        /// </summary>
        public static string txt_company_error_delete {
            get {
                return ResourceManager.GetString("txt_company_error_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de validación en el formulario.
        /// </summary>
        public static string txt_company_error_form {
            get {
                return ResourceManager.GetString("txt_company_error_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al registrar la compañía.
        /// </summary>
        public static string txt_company_error_saved {
            get {
                return ResourceManager.GetString("txt_company_error_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al editar la compañía.
        /// </summary>
        public static string txt_company_error_updated {
            get {
                return ResourceManager.GetString("txt_company_error_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar compañias con invitaciones, eliminelas para continuar.
        /// </summary>
        public static string txt_company_has_invitation {
            get {
                return ResourceManager.GetString("txt_company_has_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la empresa, porque la compañía tiene barcos o proyectos creados.
        /// </summary>
        public static string txt_company_has_vp {
            get {
                return ResourceManager.GetString("txt_company_has_vp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañía registrada con éxito.
        /// </summary>
        public static string txt_company_saved {
            get {
                return ResourceManager.GetString("txt_company_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañía actualizada con éxito.
        /// </summary>
        public static string txt_company_updated {
            get {
                return ResourceManager.GetString("txt_company_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto!.
        /// </summary>
        public static string txt_correcto {
            get {
                return ResourceManager.GetString("txt_correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string txt_email {
            get {
                return ResourceManager.GetString("txt_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes empresa asignada.
        /// </summary>
        public static string txt_empty {
            get {
                return ResourceManager.GetString("txt_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo unir a la empresa.
        /// </summary>
        public static string txt_error_confirm {
            get {
                return ResourceManager.GetString("txt_error_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al enviar las invitaciones.
        /// </summary>
        public static string txt_error_invite {
            get {
                return ResourceManager.GetString("txt_error_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al remover la invitación.
        /// </summary>
        public static string txt_error_remove_invitation {
            get {
                return ResourceManager.GetString("txt_error_remove_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La empresa &lt;b&gt;{0}&lt;/b&gt; te ha invitado a unirte como parte de sus colaboradores. ¿Deseas aceptar la invitación?.
        /// </summary>
        public static string txt_invitation_confirm {
            get {
                return ResourceManager.GetString("txt_invitation_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes seleccionar al menos un correo para invitar.
        /// </summary>
        public static string txt_invitation_empty {
            get {
                return ResourceManager.GetString("txt_invitation_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los siguientes correos ya pertenecen a una compañia: {0}.
        /// </summary>
        public static string txt_invitation_has_company {
            get {
                return ResourceManager.GetString("txt_invitation_has_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar usuarios.
        /// </summary>
        public static string txt_invitation_title {
            get {
                return ResourceManager.GetString("txt_invitation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cancelar el registro de la compañía?.
        /// </summary>
        public static string txt_mje_cancel_save {
            get {
                return ResourceManager.GetString("txt_mje_cancel_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre fiscal.
        /// </summary>
        public static string txt_name {
            get {
                return ResourceManager.GetString("txt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email del usuario.
        /// </summary>
        public static string txt_ph_invitate {
            get {
                return ResourceManager.GetString("txt_ph_invitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string txt_phone {
            get {
                return ResourceManager.GetString("txt_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se removera a este usuario de la empresas.
        /// </summary>
        public static string txt_remove_invitation {
            get {
                return ResourceManager.GetString("txt_remove_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se removió el usuario exitosamente.
        /// </summary>
        public static string txt_remove_invitation_success {
            get {
                return ResourceManager.GetString("txt_remove_invitation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        public static string txt_rfc {
            get {
                return ResourceManager.GetString("txt_rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación exitosa.
        /// </summary>
        public static string txt_succes_del {
            get {
                return ResourceManager.GetString("txt_succes_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se enviaron las invitaciones exitosamente.
        /// </summary>
        public static string txt_success_invite {
            get {
                return ResourceManager.GetString("txt_success_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Compañía.
        /// </summary>
        public static string txt_title_create {
            get {
                return ResourceManager.GetString("txt_title_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición de Compañía.
        /// </summary>
        public static string txt_title_edit {
            get {
                return ResourceManager.GetString("txt_title_edit", resourceCulture);
            }
        }
    }
}
