//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGULF.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Project {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EGULF.App_LocalResources.Project", typeof(Project).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese los datos solicitados paso por paso para completar el registro del proyecto.
        /// </summary>
        public static string CreateProjectSubtitle {
            get {
                return ResourceManager.GetString("CreateProjectSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Proyecto.
        /// </summary>
        public static string CreateProjectTitle {
            get {
                return ResourceManager.GetString("CreateProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese el motivo o razón por el cual desea cancelar el proyecto (requerido):.
        /// </summary>
        public static string DeleteProjectInstructions {
            get {
                return ResourceManager.GetString("DeleteProjectInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto se cancelará y desaparecerá de su lista de proyectos (esta acción no puede ser revertida), ¿Desea continuar?.
        /// </summary>
        public static string DeleteProjectTextConfirm {
            get {
                return ResourceManager.GetString("DeleteProjectTextConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Proyecto.
        /// </summary>
        public static string DeleteProjectTitle {
            get {
                return ResourceManager.GetString("DeleteProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes empresa asignada.
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string EmptySubject {
            get {
                return ResourceManager.GetString("EmptySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalaciones:.
        /// </summary>
        public static string LabelAmenities {
            get {
                return ResourceManager.GetString("LabelAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiro a Punto Fijo :.
        /// </summary>
        public static string LabelBollardPull {
            get {
                return ResourceManager.GetString("LabelBollardPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiro a Punto Fijo (proa):.
        /// </summary>
        public static string LabelBollardPullAhead {
            get {
                return ResourceManager.GetString("LabelBollardPullAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiro a Punto Fijo (popa):.
        /// </summary>
        public static string LabelBollardPullAstern {
            get {
                return ResourceManager.GetString("LabelBollardPullAstern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto:.
        /// </summary>
        public static string LabelBudget {
            get {
                return ResourceManager.GetString("LabelBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especificaciones de Cabina(s):.
        /// </summary>
        public static string LabelCabinSpecifications {
            get {
                return ResourceManager.GetString("LabelCabinSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de Carga:.
        /// </summary>
        public static string LabelCargoCapacity {
            get {
                return ResourceManager.GetString("LabelCargoCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de Tanque de Silos (carga a granel).
        /// </summary>
        public static string LabelCementTankCapacity {
            get {
                return ResourceManager.GetString("LabelCementTankCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List de PEMEX:.
        /// </summary>
        public static string LabelCheckPemex {
            get {
                return ResourceManager.GetString("LabelCheckPemex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información General del Proyecto.
        /// </summary>
        public static string LabelCreateStep1 {
            get {
                return ResourceManager.GetString("LabelCreateStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerimientos Específicos del Proyecto (Opcional).
        /// </summary>
        public static string LabelCreateStep2 {
            get {
                return ResourceManager.GetString("LabelCreateStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibilidad Con Barco(s).
        /// </summary>
        public static string LabelCreateStep3 {
            get {
                return ResourceManager.GetString("LabelCreateStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia en Cubierta:.
        /// </summary>
        public static string LabelDeckStrenght {
            get {
                return ResourceManager.GetString("LabelDeckStrenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad de Descarga:.
        /// </summary>
        public static string LabelDischargeRate {
            get {
                return ResourceManager.GetString("LabelDischargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble Litera:.
        /// </summary>
        public static string LabelDoubleBerth {
            get {
                return ResourceManager.GetString("LabelDoubleBerth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Duración:.
        /// </summary>
        public static string LabelDurationType {
            get {
                return ResourceManager.GetString("LabelDurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Posicionamiento Dinámico:.
        /// </summary>
        public static string LabelDynamicPositioningSystem {
            get {
                return ResourceManager.GetString("LabelDynamicPositioningSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración Estimada (Días):.
        /// </summary>
        public static string LabelEstimatedDuration {
            get {
                return ResourceManager.GetString("LabelEstimatedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posibilidad de Extensión:.
        /// </summary>
        public static string LabelExtension {
            get {
                return ResourceManager.GetString("LabelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Extensión:.
        /// </summary>
        public static string LabelExtensionType {
            get {
                return ResourceManager.GetString("LabelExtensionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuatro Literas:.
        /// </summary>
        public static string LabelFourBerth {
            get {
                return ResourceManager.GetString("LabelFourBerth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Libre de Cubierta:.
        /// </summary>
        public static string LabelFreeDeckArea {
            get {
                return ResourceManager.GetString("LabelFreeDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa Máxima Deseada:.
        /// </summary>
        public static string LabelMaxRateBudget {
            get {
                return ResourceManager.GetString("LabelMaxRateBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de Tanque de Lodo:.
        /// </summary>
        public static string LabelMudCapacity {
            get {
                return ResourceManager.GetString("LabelMudCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Pasajeros:.
        /// </summary>
        public static string LabelNumberPassengers {
            get {
                return ResourceManager.GetString("LabelNumberPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de Recuperación de Hidrocarburos:.
        /// </summary>
        public static string LabelOilRecoveryCapacity {
            get {
                return ResourceManager.GetString("LabelOilRecoveryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría del Proyecto:.
        /// </summary>
        public static string LabelProjectType {
            get {
                return ResourceManager.GetString("LabelProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de Operación:.
        /// </summary>
        public static string LabelRegion {
            get {
                return ResourceManager.GetString("LabelRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione:.
        /// </summary>
        public static string LabelSelectOne {
            get {
                return ResourceManager.GetString("LabelSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litera Individual:.
        /// </summary>
        public static string LabelSingleBerth {
            get {
                return ResourceManager.GetString("LabelSingleBerth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio:.
        /// </summary>
        public static string LabelStartDate {
            get {
                return ResourceManager.GetString("LabelStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtipo:.
        /// </summary>
        public static string LabelSubtype {
            get {
                return ResourceManager.GetString("LabelSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad del Tanque:.
        /// </summary>
        public static string LabelTankCapacity {
            get {
                return ResourceManager.GetString("LabelTankCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Extensión:.
        /// </summary>
        public static string LabelTotalExtension {
            get {
                return ResourceManager.GetString("LabelTotalExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de inicio no debe ser menor a la fecha actual (Nuevo proyecto) o a la fecha inicial registrada (Edición de proyecto).
        /// </summary>
        public static string MsgWrongStartDate {
            get {
                return ResourceManager.GetString("MsgWrongStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinas con A/C.
        /// </summary>
        public static string OptionAirConditioning {
            get {
                return ResourceManager.GetString("OptionAirConditioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejor Oferta.
        /// </summary>
        public static string OptionBestOffer {
            get {
                return ResourceManager.GetString("OptionBestOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abastecimiento de Combustible.
        /// </summary>
        public static string OptionBunkering {
            get {
                return ResourceManager.GetString("OptionBunkering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de Juntas.
        /// </summary>
        public static string OptionConferenceRoom {
            get {
                return ResourceManager.GetString("OptionConferenceRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de Control.
        /// </summary>
        public static string OptionControlRoom {
            get {
                return ResourceManager.GetString("OptionControlRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirón Convencional.
        /// </summary>
        public static string OptionConventionalTug {
            get {
                return ResourceManager.GetString("OptionConventionalTug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días:.
        /// </summary>
        public static string OptionDays {
            get {
                return ResourceManager.GetString("OptionDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP1.
        /// </summary>
        public static string OptionDP1 {
            get {
                return ResourceManager.GetString("OptionDP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP2.
        /// </summary>
        public static string OptionDP2 {
            get {
                return ResourceManager.GetString("OptionDP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DP3.
        /// </summary>
        public static string OptionDP3 {
            get {
                return ResourceManager.GetString("OptionDP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimnasio.
        /// </summary>
        public static string OptionGymnasium {
            get {
                return ResourceManager.GetString("OptionGymnasium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string OptionHospital {
            get {
                return ResourceManager.GetString("OptionHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas.
        /// </summary>
        public static string OptionHours {
            get {
                return ResourceManager.GetString("OptionHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Global.
        /// </summary>
        public static string OptionLumbsum {
            get {
                return ResourceManager.GetString("OptionLumbsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte de Material.
        /// </summary>
        public static string OptionMaterialTransportation {
            get {
                return ResourceManager.GetString("OptionMaterialTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa Diaria Máxima.
        /// </summary>
        public static string OptionMaxDailyRate {
            get {
                return ResourceManager.GetString("OptionMaxDailyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedor.
        /// </summary>
        public static string OptionMessRoom {
            get {
                return ResourceManager.GetString("OptionMessRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string OptionNo {
            get {
                return ResourceManager.GetString("OptionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Requerido.
        /// </summary>
        public static string OptionNoRequired {
            get {
                return ResourceManager.GetString("OptionNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficinas.
        /// </summary>
        public static string OptionOffices {
            get {
                return ResourceManager.GetString("OptionOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte de Personal o Flotel.
        /// </summary>
        public static string OptionPersonnelTransportation {
            get {
                return ResourceManager.GetString("OptionPersonnelTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerido.
        /// </summary>
        public static string OptionRequired {
            get {
                return ResourceManager.GetString("OptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remolcador de Popa.
        /// </summary>
        public static string OptionSternDriveTug {
            get {
                return ResourceManager.GetString("OptionSternDriveTug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piscina.
        /// </summary>
        public static string OptionSwimingPool {
            get {
                return ResourceManager.GetString("OptionSwimingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remolque.
        /// </summary>
        public static string OptionTowage {
            get {
                return ResourceManager.GetString("OptionTowage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string OptionYes {
            get {
                return ResourceManager.GetString("OptionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string PagerTitle {
            get {
                return ResourceManager.GetString("PagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M2).
        /// </summary>
        public static string PlaceholderM2 {
            get {
                return ResourceManager.GetString("PlaceholderM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M3).
        /// </summary>
        public static string PlaceholderM3 {
            get {
                return ResourceManager.GetString("PlaceholderM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M3) o Galones.
        /// </summary>
        public static string PlaceholderM3Gallons {
            get {
                return ResourceManager.GetString("PlaceholderM3Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (M3/h).
        /// </summary>
        public static string PlaceholderM3H {
            get {
                return ResourceManager.GetString("PlaceholderM3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (T/m).
        /// </summary>
        public static string PlaceholderMT {
            get {
                return ResourceManager.GetString("PlaceholderMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (T/m2).
        /// </summary>
        public static string PlaceholderTM2 {
            get {
                return ResourceManager.GetString("PlaceholderTM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (T).
        /// </summary>
        public static string PlaceholderTonnes {
            get {
                return ResourceManager.GetString("PlaceholderTonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría del Proyecto.
        /// </summary>
        public static string ProjectCategoryTitle {
            get {
                return ResourceManager.GetString("ProjectCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string TableHeaderActions {
            get {
                return ResourceManager.GetString("TableHeaderActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        public static string TableHeaderCategory {
            get {
                return ResourceManager.GetString("TableHeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string TableHeaderDuration {
            get {
                return ResourceManager.GetString("TableHeaderDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        public static string TableHeaderId {
            get {
                return ResourceManager.GetString("TableHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string TableHeaderStartDate {
            get {
                return ResourceManager.GetString("TableHeaderStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string TableHeaderStatus {
            get {
                return ResourceManager.GetString("TableHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione las comodidades disponibles para los pasajeros abordo de la embarcación.
        /// </summary>
        public static string TooltipAmenities {
            get {
                return ResourceManager.GetString("TooltipAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tirón a punto fijo es la medida convencional de poder de tirón (remolcamiento) de una embarcación.
        /// </summary>
        public static string TooltipBollarPull {
            get {
                return ResourceManager.GetString("TooltipBollarPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El check-list de PEMEX es una inspección fisico-documental que se le realiza a cualquier embarcación para garantizar que cumpla con los parametros minimos de seguridad y así permitirle el acceso al area de plataformas.
        /// </summary>
        public static string TooltipCheckPemex {
            get {
                return ResourceManager.GetString("TooltipCheckPemex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema de posicionamiento dinámico es un sistema controlado por computadora para mantener la posición y grado de un barco de manera automática.
        /// </summary>
        public static string TooltipDynamicPositioningSystem {
            get {
                return ResourceManager.GetString("TooltipDynamicPositioningSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TooltipEstimatedDuration {
            get {
                return ResourceManager.GetString("TooltipEstimatedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número en métros cúbicos o en galones.
        /// </summary>
        public static string TooltipM3Gallons {
            get {
                return ResourceManager.GetString("TooltipM3Gallons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número en métros cúbicos por hora.
        /// </summary>
        public static string TooltipM3H {
            get {
                return ResourceManager.GetString("TooltipM3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad total de personal a mover, puede ser superior a la capacidad de la embarcación.
        /// </summary>
        public static string TooltipNumberPassengersPersonelTransportation {
            get {
                return ResourceManager.GetString("TooltipNumberPassengersPersonelTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría del proyecto. Escoger el alcance principal del proyecto.
        /// </summary>
        public static string TooltipProjectType {
            get {
                return ResourceManager.GetString("TooltipProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medida en métros cúbicos.
        /// </summary>
        public static string TooltipsCubicMeters {
            get {
                return ResourceManager.GetString("TooltipsCubicMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medida en métros cuadrados.
        /// </summary>
        public static string TooltipSquareMeters {
            get {
                return ResourceManager.GetString("TooltipSquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha estimada de inicio del proyecto.
        /// </summary>
        public static string TooltipStartDate {
            get {
                return ResourceManager.GetString("TooltipStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toneladas en metros cuadrados.
        /// </summary>
        public static string TooltipTM2 {
            get {
                return ResourceManager.GetString("TooltipTM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medida en Toneladas.
        /// </summary>
        public static string TooltipTonnes {
            get {
                return ResourceManager.GetString("TooltipTonnes", resourceCulture);
            }
        }
    }
}
