//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGULF.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SingUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SingUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EGULF.App_LocalResources.SingUp", typeof(SingUp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string BtnTextRegister {
            get {
                return ResourceManager.GetString("BtnTextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string BtnTextRegisterConfirmed {
            get {
                return ResourceManager.GetString("BtnTextRegisterConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea una cuenta.
        /// </summary>
        public static string HeaderCreateAccount {
            get {
                return ResourceManager.GetString("HeaderCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información general.
        /// </summary>
        public static string HeaderGeneralInformation {
            get {
                return ResourceManager.GetString("HeaderGeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de usuario.
        /// </summary>
        public static string HeaderUserInformation {
            get {
                return ResourceManager.GetString("HeaderUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su datos para poder iniciar sesión en egulf.
        /// </summary>
        public static string HelpTextCreateAccount {
            get {
                return ResourceManager.GetString("HelpTextCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email ingresado ya ha sido registrado y no está disponible.
        /// </summary>
        public static string MsgEmailExisting {
            get {
                return ResourceManager.GetString("MsgEmailExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ingresado ya ha sido registrado y no está disponible.
        /// </summary>
        public static string MsgUserExisting {
            get {
                return ResourceManager.GetString("MsgUserExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un formato de email válido (ejemplo@email.com).
        /// </summary>
        public static string MsgWrongEmailFormat {
            get {
                return ResourceManager.GetString("MsgWrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string MsgWrongPasswordConfirmation {
            get {
                return ResourceManager.GetString("MsgWrongPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario aceptar los términos y condiciones.
        /// </summary>
        public static string MsgWrongTermAndCondition {
            get {
                return ResourceManager.GetString("MsgWrongTermAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string PlaceholderEmail {
            get {
                return ResourceManager.GetString("PlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre(s).
        /// </summary>
        public static string PlaceholderFirstName {
            get {
                return ResourceManager.GetString("PlaceholderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string PlaceholderLastName {
            get {
                return ResourceManager.GetString("PlaceholderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string PlaceholderPassword {
            get {
                return ResourceManager.GetString("PlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir contraseña.
        /// </summary>
        public static string PlaceholderRepeatPassword {
            get {
                return ResourceManager.GetString("PlaceholderRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string PlaceholderSkype {
            get {
                return ResourceManager.GetString("PlaceholderSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string PlaceholderTelefono {
            get {
                return ResourceManager.GetString("PlaceholderTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string PlaceholderUsername {
            get {
                return ResourceManager.GetString("PlaceholderUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He leído y acepto los.
        /// </summary>
        public static string TextAgree {
            get {
                return ResourceManager.GetString("TextAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya tiene una cuenta?.
        /// </summary>
        public static string TextHaveAccount {
            get {
                return ResourceManager.GetString("TextHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        public static string TextTermAndCondition {
            get {
                return ResourceManager.GetString("TextTermAndCondition", resourceCulture);
            }
        }
    }
}
