//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGULF.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Support {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EGULF.App_LocalResources.Support", typeof(Support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string HelpEmail {
            get {
                return ResourceManager.GetString("HelpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese sus datos de contacto junto con la información detallada de su problema, el equipo E-GULF le contactará para ayudarle a solucionarlo lo más pronto posible:.
        /// </summary>
        public static string HelpInfo {
            get {
                return ResourceManager.GetString("HelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese la información detallada de su problema, el equipo E-GULF le contactará enviando un mensaje al correo asociado a su cuenta para ayudarle a solucionarlo lo más pronto posible:.
        /// </summary>
        public static string HelpInfoSession {
            get {
                return ResourceManager.GetString("HelpInfoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string HelpName {
            get {
                return ResourceManager.GetString("HelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Gracias por contactarnos!, procederemos a verificar su mensaje y le responderemos lo más pronto posible con una solución a su problema..
        /// </summary>
        public static string HelpServiceConfirmed {
            get {
                return ResourceManager.GetString("HelpServiceConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por el momento el servicio de Ayuda y Soporte no está disponible..
        /// </summary>
        public static string HelpServiceNotAvailable {
            get {
                return ResourceManager.GetString("HelpServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe tu problema.
        /// </summary>
        public static string HelpSubtitle {
            get {
                return ResourceManager.GetString("HelpSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Correo a Soporte E-GULF.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
    }
}
