//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGULF.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vessels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vessels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EGULF.App_LocalResources.Vessels", typeof(Vessels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionales.
        /// </summary>
        public static string Aditionals {
            get {
                return ResourceManager.GetString("Aditionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aire acondicionado.
        /// </summary>
        public static string AirCondition {
            get {
                return ResourceManager.GetString("AirCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenidades.
        /// </summary>
        public static string Amenities {
            get {
                return ResourceManager.GetString("Amenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibilidad.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se permiten imágenes en formato (jpeg, jpg, png).
        /// </summary>
        public static string BadExtension {
            get {
                return ResourceManager.GetString("BadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de agua de lastre.
        /// </summary>
        public static string BallastWaterCapacity {
            get {
                return ResourceManager.GetString("BallastWaterCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga total.
        /// </summary>
        public static string BeamOverall {
            get {
                return ResourceManager.GetString("BeamOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el ancho máximo del buque medido desde la superficie exterior del casco..
        /// </summary>
        public static string BeamOverallDescription {
            get {
                return ResourceManager.GetString("BeamOverallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHP.
        /// </summary>
        public static string BHP {
            get {
                return ResourceManager.GetString("BHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHP.
        /// </summary>
        public static string BHPDescription {
            get {
                return ResourceManager.GetString("BHPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiron a punto fijo.
        /// </summary>
        public static string BollardPull {
            get {
                return ResourceManager.GetString("BollardPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiron a punto fijo (proa).
        /// </summary>
        public static string BollardPullAhead {
            get {
                return ResourceManager.GetString("BollardPullAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es la medida de la cantidad de fuerza que un remolcador es capaz de aplicar en un trabajo de remolque..
        /// </summary>
        public static string BollardPullAheadDescription {
            get {
                return ResourceManager.GetString("BollardPullAheadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiron a popa.
        /// </summary>
        public static string BollardPullAstern {
            get {
                return ResourceManager.GetString("BollardPullAstern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es la medida de la cantidad de fuerza que un remolcador es capaz de aplicar en un trabajo de remolque..
        /// </summary>
        public static string BollardPullAsternDescription {
            get {
                return ResourceManager.GetString("BollardPullAsternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es la medida de la cantidad de fuerza que un remolcador es capaz de aplicar en un trabajo de remolque..
        /// </summary>
        public static string BollardPullDescription {
            get {
                return ResourceManager.GetString("BollardPullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especificación de cabinas.
        /// </summary>
        public static string CabinsSpecification {
            get {
                return ResourceManager.GetString("CabinsSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de carga en cubierta.
        /// </summary>
        public static string CargoCapacity {
            get {
                return ResourceManager.GetString("CargoCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de Silos (carga a granel).
        /// </summary>
        public static string CementTanksCapacity {
            get {
                return ResourceManager.GetString("CementTanksCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociedad clasificadora del barco.
        /// </summary>
        public static string ClassDescription {
            get {
                return ResourceManager.GetString("ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notación de la clase.
        /// </summary>
        public static string ClassNotation {
            get {
                return ResourceManager.GetString("ClassNotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especificaciones de clase.
        /// </summary>
        public static string ClassNotationDescription {
            get {
                return ResourceManager.GetString("ClassNotationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez de clase.
        /// </summary>
        public static string ClassValidity {
            get {
                return ResourceManager.GetString("ClassValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de expiración del certificado de clase.
        /// </summary>
        public static string ClassValidityDescription {
            get {
                return ResourceManager.GetString("ClassValidityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala de juntas.
        /// </summary>
        public static string ConferenceRoom {
            get {
                return ResourceManager.GetString("ConferenceRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuarto de control.
        /// </summary>
        public static string ControlRoom {
            get {
                return ResourceManager.GetString("ControlRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandera.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País de registro del barco.
        /// </summary>
        public static string CountryDescription {
            get {
                return ResourceManager.GetString("CountryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad económica.
        /// </summary>
        public static string CruisingSpeed {
            get {
                return ResourceManager.GetString("CruisingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadruple.
        /// </summary>
        public static string Cuadruple {
            get {
                return ResourceManager.GetString("Cuadruple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costos.
        /// </summary>
        public static string DailyRate {
            get {
                return ResourceManager.GetString("DailyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa diaria flotel.
        /// </summary>
        public static string DailyRateFlotel {
            get {
                return ResourceManager.GetString("DailyRateFlotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa diaria transporte material.
        /// </summary>
        public static string DailyRateMaterialTransportation {
            get {
                return ResourceManager.GetString("DailyRateMaterialTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa diaria transporte personal.
        /// </summary>
        public static string DailyRatePersonnelTransportation {
            get {
                return ResourceManager.GetString("DailyRatePersonnelTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifa diaria remolque.
        /// </summary>
        public static string DailyRateTowing {
            get {
                return ResourceManager.GetString("DailyRateTowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia de cubierta.
        /// </summary>
        public static string DeckStrenght {
            get {
                return ResourceManager.GetString("DeckStrenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad en toneladas por metro cuadrado de la cubierta.
        /// </summary>
        public static string DeckStrenghtDescription {
            get {
                return ResourceManager.GetString("DeckStrenghtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DischargeRate.
        /// </summary>
        public static string DischargeRate {
            get {
                return ResourceManager.GetString("DischargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DischargeRate.
        /// </summary>
        public static string DischargeRateDescription {
            get {
                return ResourceManager.GetString("DischargeRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomía en velocidad económica.
        /// </summary>
        public static string DistanceCruisingSpeed {
            get {
                return ResourceManager.GetString("DistanceCruisingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomía en velocidad máxima.
        /// </summary>
        public static string DistanceMaxSpeed {
            get {
                return ResourceManager.GetString("DistanceMaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doble.
        /// </summary>
        public static string Double {
            get {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de posicionamiento dinámico.
        /// </summary>
        public static string DynamicPositionSystem {
            get {
                return ResourceManager.GetString("DynamicPositionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error. .
        /// </summary>
        public static string ErrorOnSave {
            get {
                return ResourceManager.GetString("ErrorOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información adicional.
        /// </summary>
        public static string ExtraInfo {
            get {
                return ResourceManager.GetString("ExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área libre de cubierta.
        /// </summary>
        public static string FreeDeckArea {
            get {
                return ResourceManager.GetString("FreeDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area de cubierta en metros cuadrados..
        /// </summary>
        public static string FreeDeckAreaDescription {
            get {
                return ResourceManager.GetString("FreeDeckAreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de agua potable.
        /// </summary>
        public static string FreshWaterCapacity {
            get {
                return ResourceManager.GetString("FreshWaterCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo diario de combustible en velocidad económica.
        /// </summary>
        public static string FuelConsumptionCruisingSpeed {
            get {
                return ResourceManager.GetString("FuelConsumptionCruisingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo de combustible, en metros cubicos, en velocidad económica.
        /// </summary>
        public static string FuelConsumptionCruisingSpeedDescription {
            get {
                return ResourceManager.GetString("FuelConsumptionCruisingSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo diario de combustible en velocidad máxima.
        /// </summary>
        public static string FuelConsumptionMaxSpeed {
            get {
                return ResourceManager.GetString("FuelConsumptionMaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo de combustible, en metros cubicos, en velocidad máxima.
        /// </summary>
        public static string FuelConsumptionMaxSpeedDescription {
            get {
                return ResourceManager.GetString("FuelConsumptionMaxSpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de combustible.
        /// </summary>
        public static string FuelOilCapacity {
            get {
                return ResourceManager.GetString("FuelOilCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información general.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonelaje bruto.
        /// </summary>
        public static string GrossTonnage {
            get {
                return ResourceManager.GetString("GrossTonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el volumen del buque entre el plan y la cubierta alta con todos los espacios cerrados..
        /// </summary>
        public static string GrossTonnageDescription {
            get {
                return ResourceManager.GetString("GrossTonnageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimnasio.
        /// </summary>
        public static string Gym {
            get {
                return ResourceManager.GetString("Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calentador de agua.
        /// </summary>
        public static string HotWaterCalorifier {
            get {
                return ResourceManager.GetString("HotWaterCalorifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMO .
        /// </summary>
        public static string Imo {
            get {
                return ResourceManager.GetString("Imo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un número de siete dígitos.
        /// </summary>
        public static string InvalidIMO {
            get {
                return ResourceManager.GetString("InvalidIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo de lavandería.
        /// </summary>
        public static string LaundryCost {
            get {
                return ResourceManager.GetString("LaundryCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eslora total.
        /// </summary>
        public static string LengthOverall {
            get {
                return ResourceManager.GetString("LengthOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es la distancia comprendida entre las perpendiculares de los puntos más salientes del buque en al plano longitudinal.
        ///.
        /// </summary>
        public static string LengthOverallDescription {
            get {
                return ResourceManager.GetString("LengthOverallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo de acomodación.
        /// </summary>
        public static string LodgingCost {
            get {
                return ResourceManager.GetString("LodgingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar.
        /// </summary>
        public static string ManageVessel {
            get {
                return ResourceManager.GetString("ManageVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportación de material.
        /// </summary>
        public static string MaterialTransportation {
            get {
                return ResourceManager.GetString("MaterialTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calado a carga máxima.
        /// </summary>
        public static string MaximumLoadedDraft {
            get {
                return ResourceManager.GetString("MaximumLoadedDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es la distancia vertical medida desde el plano que pasa por la parte más baja de la quilla hasta la línea de agua a la que está flotando el buque..
        /// </summary>
        public static string MaximumLoadedDraftDescription {
            get {
                return ResourceManager.GetString("MaximumLoadedDraftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad máxima.
        /// </summary>
        public static string MaximumSpeed {
            get {
                return ResourceManager.GetString("MaximumSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo de alimentación.
        /// </summary>
        public static string MealCost {
            get {
                return ResourceManager.GetString("MealCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedor.
        /// </summary>
        public static string MessRoom {
            get {
                return ResourceManager.GetString("MessRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de tanques de lodo.
        /// </summary>
        public static string MudCapacity {
            get {
                return ResourceManager.GetString("MudCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonelaje neto.
        /// </summary>
        public static string NetTonnage {
            get {
                return ResourceManager.GetString("NetTonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el volumen - en toneladas de arqueo - de los espacios destinados al cargamento..
        /// </summary>
        public static string NetTonnageDescription {
            get {
                return ResourceManager.GetString("NetTonnageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string NewVessel {
            get {
                return ResourceManager.GetString("NewVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin información adicional.
        /// </summary>
        public static string NoExtraInfo {
            get {
                return ResourceManager.GetString("NoExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de pasajeros.
        /// </summary>
        public static string NumberPassenger {
            get {
                return ResourceManager.GetString("NumberPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de recuperación de hidrocarburos.
        /// </summary>
        public static string OilRecoveryCapacity {
            get {
                return ResourceManager.GetString("OilRecoveryCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist de PEMEX.
        /// </summary>
        public static string PemexCheck {
            get {
                return ResourceManager.GetString("PemexCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El check-list de PEMEX es una inspección fisico-documental que se le realiza a cualquier embarcación para garantizar que cumpla con los parametros minimos de seguridad y así permitirle el acceso al area de plataformas.
        /// </summary>
        public static string PemexCheckDescription {
            get {
                return ResourceManager.GetString("PemexCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte de personal o flotel.
        /// </summary>
        public static string PersonnelTransportation {
            get {
                return ResourceManager.GetString("PersonnelTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piscina.
        /// </summary>
        public static string Pool {
            get {
                return ResourceManager.GetString("Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string PoolDescription {
            get {
                return ResourceManager.GetString("PoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto .
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto base.
        /// </summary>
        public static string PortDescription {
            get {
                return ResourceManager.GetString("PortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidad de Bombeo.
        /// </summary>
        public static string PumpRates {
            get {
                return ResourceManager.GetString("PumpRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar barco.
        /// </summary>
        public static string RegisterVessel {
            get {
                return ResourceManager.GetString("RegisterVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMO no disponible.
        /// </summary>
        public static string RepeatedIMO {
            get {
                return ResourceManager.GetString("RepeatedIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre no disponible.
        /// </summary>
        public static string RepeatedName {
            get {
                return ResourceManager.GetString("RepeatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta de tratamiento de aguas negras.
        /// </summary>
        public static string SewageTreatmentPlant {
            get {
                return ResourceManager.GetString("SewageTreatmentPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información específica.
        /// </summary>
        public static string SpecificInfo {
            get {
                return ResourceManager.GetString("SpecificInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoría.
        /// </summary>
        public static string SubtypeId {
            get {
                return ResourceManager.GetString("SubtypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adecuabilidad.
        /// </summary>
        public static string Suitability {
            get {
                return ResourceManager.GetString("Suitability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de servicios que el barco puede ejecutar.
        /// </summary>
        public static string SuitabilityDescription {
            get {
                return ResourceManager.GetString("SuitabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remolque.
        /// </summary>
        public static string Towage {
            get {
                return ResourceManager.GetString("Towage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple.
        /// </summary>
        public static string Triple {
            get {
                return ResourceManager.GetString("Triple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barco.
        /// </summary>
        public static string Vessel {
            get {
                return ResourceManager.GetString("Vessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo barco.
        /// </summary>
        public static string VesselType {
            get {
                return ResourceManager.GetString("VesselType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de barco.
        /// </summary>
        public static string VesselTypeDescription {
            get {
                return ResourceManager.GetString("VesselTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta potabilizadora.
        /// </summary>
        public static string WaterMarkerPlant {
            get {
                return ResourceManager.GetString("WaterMarkerPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año de construcción.
        /// </summary>
        public static string YearBuild {
            get {
                return ResourceManager.GetString("YearBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año de construcción del barco.
        /// </summary>
        public static string YearBuildDescription {
            get {
                return ResourceManager.GetString("YearBuildDescription", resourceCulture);
            }
        }
    }
}
