//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGullf.Services.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTemplateSection
    {
        public int CustomTemplateSectionId { get; set; }
        public Nullable<int> CustomTemplateId { get; set; }
        public string SectionKey { get; set; }
        public string SectionValue { get; set; }
    }
}
