//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGullf.Services.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemVariable
    {
        public int VariableId { get; set; }
        public string VariableName { get; set; }
        public string Value { get; set; }
        public string Entity { get; set; }
        public string Description { get; set; }
    }
}
